- name: Configure MariaDB step 1.
  ansible.builtin.template:
    backup: true
    src: "templates/{{ mariadb_cnf }}"
    dest: "/etc/my.cnf.d/mariadb-server.cnf"

- name: Configure MariaDB step 2.
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
    enabled: true

# This is trying to give root user info
- name: Configure MariaDB step 3.
  ansible.builtin.template:
    backup: true
    src: "templates/{{ mysql_root_cnf }}"
    dest: "root/.my.cnf"
    owner: root
    mode: '0600'

- name: Configure MariaDB step 4.
  community.mysql.mysql_db:
    name: librenms
    state: present
    login_user: root
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci

- name: Configure MariaDB step 5.
  community.mysql.mysql_user:
    state: present
    name: librenms
    host: localhost
    password: "{{ LIBRENMS_DB_PASSWORD }}"
    priv: 'librenms.*:ALL,GRANT'
    login_user: root
    
